### ISSUE TITLE
Usage in nodejs

### ISSUE THREAD

**Issue by hvincente** [svenwiegand/typed-intl#1]
Hi,

i would like to know if there is a possibility to use this library in a nodejs application.
 Navigator object is used to get default browser languages but its not defined in node js.

Thanks

**Comment by svenwiegand** [comment]
I don't have experience with node.js, but I would expect this to work. `navigator.language` is only used to automatically determine the preferred language, but the library only uses it, if it is defined. Thus if you define `navigator.language` as `undefined`, everything should be working fine. Only thing you need to do is calling `setPreferredLanguage()` manually to set the language. You still can use `pickPreferredLanguage()` as a helper.

Let me know whether this works or if changes are required for node.js.

**Comment by hvincente** [comment]
I am new to typescript and node, so i don't understand the error well.
But at build time i have got a > ReferenceError: navigator is not `defined`.
Typescript compiler doesn't know anything about the navigator object.
I have clone the lib and make a little change. 
Instead of a check on navigator i add typeof navigator !== 'undefined' for _preferredLanguage and navigatorLanguages and it works.
ex: condition `navigator.language` becomes `typeof navigator !== 'undefined' && navigator.language.`

A workaround is to declare navigator object as global to not have this error.
This library make all definitions for a browser environment in nodejs 
[https://github.com/rstacruz/jsdom-global](url)

**Comment by svenwiegand** [comment]
Thanks for the hint. I've published a new release `1.0.1` which dynamically accesses the `navigator` object and checks whether it is defined. Thus the lib should now work without any hassle on node.js. Can you please confirm?

**Comment by hvincente** [comment]
Thanks for response. It cannot actually work because window object does not exists in node environment (same problem as navigator).

**Comment by svenwiegand** [comment]
Man, that was smart from me...

**Comment by svenwiegand** [comment]
I've now published version `1.0.2` which should fix the issue as described in your comment above. Could you please check again?
